name: task-checker
on:
  push:
    branches-ignore:
      - main
jobs:
    check:
        runs-on: ubuntu-latest
        env:
          TaskPath: "./tasks/${{ github.ref_name }}"
          InputFileName: input
          OutputFileName: output
          TestsCount: 3
          ProgramName: task
        steps:
            - name: check tests count
              run: |
                case ${{ github.ref_name }} in
                "task7" | "task10")
                  echo "TestsCount=6" >> $GITHUB_ENV
                  ;;
                esac
            - name: copy files
              uses: actions/checkout@v4
            - name: install
              run: sudo apt update && sudo apt install build-essential
            - name: build
              run: |
                g++ -c $(find . -maxdepth 1 -type f -name "*.cpp")
                g++ $(find . -maxdepth 1 -type f -name "*.o") -o ${ProgramName}
            - name: test
              run: |
                for (( i=1; i<=${TestsCount}; i++ ))
                do
                  "./${ProgramName}" "${TaskPath}/${InputFileName}${i}.txt" "${OutputFileName}${i}.txt"
                done
            - name: check
              run: |
                for (( i=1; i<=${TestsCount}; i++ ))
                do
                  echo "test ${i}"
                  diff "${OutputFileName}${i}.txt" "${TaskPath}/${OutputFileName}${i}.txt"
                  echo ok
                done
